### Data Cleaning using numpy
The following are the student marks of a class
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]

In [1]:
import numpy as np

In [2]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [3]:
np.isnan(marks)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

### 1.Find the no of outliers and missing values?

In [4]:
len(marks[np.isnan(marks)])  # missing values

4

In [6]:
cond = (marks>100) | (marks < 0) # outliers
cond

array([False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [7]:
len(marks[cond])

3

### 2.replace the outliers with 45 and missing value with 87.

In [8]:
m = np.array([np.where(np.isnan(marks),87,marks)],dtype = "int16") # missing value
m

array([[ 44,  24,  87,  59,  32,  96, 188,  52,  62,  58,  52, 120,  87,
         87,   3,  56,  81,  59, 122,  92,  87,  87,  96,  97,   1,  19,
          2,  53,  44]], dtype=int16)

In [9]:
marks1 = np.where(cond,45,m)
marks1

array([[44, 24, 87, 59, 32, 96, 45, 52, 62, 58, 52, 45, 87, 87,  3, 56,
        81, 59, 45, 92, 87, 87, 96, 97,  1, 19,  2, 53, 44]], dtype=int16)

### 3.what is the average marks of students after 2nd step?

In [11]:
np.mean(marks1)

56.96551724137931

### 4.How many students got less than 60 marks?


In [12]:
len(marks1[marks1 < 60])

18

### 5.what is the maximum marks?

In [13]:
np.max(marks1)

97

### 6.Convert the marks to float32.

In [14]:
np.array(marks1,dtype = "float64")

array([[44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
        87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
         2., 53., 44.]])

### Solving Linear Equations

In [15]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
a

array([[ 2,  3, -1],
       [ 1, -1,  2],
       [ 3,  2,  1]])

In [16]:
b = np.array([10,5,12])
b

array([10,  5, 12])

In [17]:
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

In [18]:
a = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
a

array([[ 2,  1, -1,  3],
       [ 3, -2,  2,  2],
       [ 1,  3, -2,  1],
       [ 4, -1,  1, -2]])

In [19]:
b = np.array([8,1,7,3])
b

array([8, 1, 7, 3])

In [20]:
np.linalg.solve(a,b)


array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [21]:
a = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
a

array([[ 4,  2, -3],
       [-2,  3,  1],
       [ 1, -1,  2]])

In [22]:
b = np.array([10,-3,4])
b

array([10, -3,  4])

In [23]:
np.linalg.solve(a,b)

array([2.85365854, 0.6097561 , 0.87804878])

### Conditional Selection with np.where()


### 1.Generate a random 1D array A of 10 integers between 1 and 100.


In [24]:
arr1 = np.random.randint(1,100,10)
A = np.array(arr1)
A

array([88, 64, 39, 55, 53, 60, 64, 90, 16, 34])

### 2.Use np.where() to find the indices where the elements of A are greater than 50.


In [25]:
cond = A>50
print(A[cond])
np.where(cond)

[88 64 55 53 60 64 90]


(array([0, 1, 3, 4, 5, 6, 7], dtype=int64),)

### 3.Create a new array B that contains elements from A where the condition is met.


In [26]:
B = np.array(A[A>50])
B

array([88, 64, 55, 53, 60, 64, 90])

### 4.Calculate the mean of array B and print it along with arrays A and B.


In [27]:
np.mean(B)  # mean

67.71428571428571

In [28]:
np.mean(A)  # mean

56.3

### Replace Values with np.where()
### 1.Create a 4x4 random integer matrix C with values between -10 and 10

In [29]:
c = np.random.randint(-10,10,16).reshape(4,4)
c

array([[-9,  9,  4,  8],
       [ 4, -9, -3, -7],
       [ 3,  6,  5,  7],
       [-9,  3, -6,  0]])

### 2.Use np.where() to replace all negative values in matrix C with 0


In [30]:
modified = np.where(c < 0,0,c)
modified

array([[0, 9, 4, 8],
       [4, 0, 0, 0],
       [3, 6, 5, 7],
       [0, 3, 0, 0]])

### 3.Print the original matrix C and the modified matrix.


In [31]:
c

array([[-9,  9,  4,  8],
       [ 4, -9, -3, -7],
       [ 3,  6,  5,  7],
       [-9,  3, -6,  0]])

In [32]:
modified


array([[0, 9, 4, 8],
       [4, 0, 0, 0],
       [3, 6, 5, 7],
       [0, 3, 0, 0]])